# docker build --rm -t drone/drone-server -f Dockerfile.server .

FROM debian:8
COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
EXPOSE 8000 9000 80 443

ENV DATABASE_DRIVER=sqlite3
ENV DATABASE_CONFIG=/var/lib/drone/drone.sqlite
ENV GODEBUG=netdns=go
ENV XDG_CACHE_HOME /var/lib/drone

ADD release/drone-server /bin/

ENTRYPOINT ["/bin/drone-server"]
